---
- hosts: localhost
  gather_facts: False
  tasks:    
    - name: Delete "{{ record }}"
      community.aws.route53:
        alias: True
        alias_hosted_zone_id: "{{ alias_zone }}"
        zone: "{{ zone }}"
        state: absent
        record: "{{ record }}"
        type: A
        value: "{{ endpoint_url }}"